2013-01-10T08:54:40+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:06:42+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:07:31+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:09:22+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:14:55+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:54:11+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:55:36+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "ajaxvalidateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('ajaxvalidateins...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('ajaxvalidateins...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:55:57+01:00 INFO (6): exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (validateInscription)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#4 {main}
2013-01-10T09:56:08+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:56:09+01:00 INFO (6): exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (css)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#4 {main}
2013-01-10T09:56:26+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:57:19+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "validateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('validateinscrip...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T09:57:32+01:00 INFO (6): exception 'Zend_Loader_PluginLoader_Exception' with message 'Plugin by name 'GetRequest' was not found in the registry; used paths:
Front_View_Helper_: /home/www/zendphpcertify/application/Front/views/helpers/
Zend_View_Helper_: Zend/View/Helper/' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Loader/PluginLoader.php:412
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(1182): Zend_Loader_PluginLoader->load('GetRequest')
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(618): Zend_View_Abstract->_getPlugin('helper', 'getRequest')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(344): Zend_View_Abstract->getHelper('getRequest')
#3 /home/www/zendphpcertify/application/Front/views/scripts/index/validateinscription.phtml(3): Zend_View_Abstract->__call('getRequest', Array)
#4 /home/www/zendphpcertify/application/Front/views/scripts/index/validateinscription.phtml(3): Zend_View->getRequest()
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View.php(108): include('/home/www/zendp...')
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(888): Zend_View->_run('/home/www/zendp...')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('index/validatei...')
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/validatei...', NULL)
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#10 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#11 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#12 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#13 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#14 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#15 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#16 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#17 {main}
2013-01-10T09:57:32+01:00 INFO (6): exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (css)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#4 {main}
2013-01-10T09:58:53+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "ajaxvalidateinscription" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('ajaxvalidateins...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('ajaxvalidateins...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T10:41:27+01:00 INFO (6): exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u_password' in 'field list'' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(575): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `us...', Array)
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Table/Abstract.php(1075): Zend_Db_Adapter_Abstract->insert('users', Array)
#6 /home/www/zendphpcertify/application/Core/models/mappers/Abstract.php(88): Zend_Db_Table_Abstract->insert(Array)
#7 /home/www/zendphpcertify/application/Front/controllers/IndexController.php(44): Core_Model_Mapper_Abstract->save(Object(Core_Model_User))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(516): Front_IndexController->validateinscriptionAction()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#10 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#11 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#12 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#13 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#14 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u_password' in 'field list'' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `us...', Array)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(575): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `us...', Array)
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Table/Abstract.php(1075): Zend_Db_Adapter_Abstract->insert('users', Array)
#5 /home/www/zendphpcertify/application/Core/models/mappers/Abstract.php(88): Zend_Db_Table_Abstract->insert(Array)
#6 /home/www/zendphpcertify/application/Front/controllers/IndexController.php(44): Core_Model_Mapper_Abstract->save(Object(Core_Model_User))
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(516): Front_IndexController->validateinscriptionAction()
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#11 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#12 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#13 {main}
2013-01-10T11:27:31+01:00 INFO (6): exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zendphpcertify.user' doesn't exist' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#4 /home/www/zendphpcertify/application/Core/models/mappers/User.php(89): Zend_Db_Adapter_Pdo_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#5 /home/www/zendphpcertify/application/Front/controllers/IndexController.php(46): Core_Model_Mapper_User->selectColum('nicolas.laratte...')
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(516): Front_IndexController->validateinscriptionAction()
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#12 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zendphpcertify.user' doesn't exist' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#3 /home/www/zendphpcertify/application/Core/models/mappers/User.php(89): Zend_Db_Adapter_Pdo_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#4 /home/www/zendphpcertify/application/Front/controllers/IndexController.php(46): Core_Model_Mapper_User->selectColum('nicolas.laratte...')
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(516): Front_IndexController->validateinscriptionAction()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-10T11:27:44+01:00 INFO (6): exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zendphpcertify.user' doesn't exist' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#4 /home/www/zendphpcertify/application/Core/models/mappers/User.php(89): Zend_Db_Adapter_Pdo_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#5 /home/www/zendphpcertify/application/Front/controllers/IndexController.php(46): Core_Model_Mapper_User->selectColum('nicolas.laratte...')
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(516): Front_IndexController->validateinscriptionAction()
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#10 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#11 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#12 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zendphpcertify.user' doesn't exist' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Statement.php(320): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#3 /home/www/zendphpcertify/application/Core/models/mappers/User.php(89): Zend_Db_Adapter_Pdo_Abstract->query('SELECT user_ema...', 'nicolas.laratte...')
#4 /home/www/zendphpcertify/application/Front/controllers/IndexController.php(46): Core_Model_Mapper_User->selectColum('nicolas.laratte...')
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(516): Front_IndexController->validateinscriptionAction()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('validateinscrip...')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-10T12:31:32+01:00 INFO (6): exception 'Zend_View_Exception' with message 'script 'index/loginvalidate.phtml' not found in path (/home/www/zendphpcertify/application/Front/views/scripts/)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php:988
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('index/loginvali...')
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('index/loginvali...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/loginvali...', NULL)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('loginvalidateAc...')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-10T15:01:25+01:00 INFO (6): exception 'Zend_View_Exception' with message 'script 'index/home-user.phtml' not found in path (/home/www/zendphpcertify/application/Front/views/scripts/)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php:988
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('index/home-user...')
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('index/home-user...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/home-user...', NULL)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-10T15:01:38+01:00 INFO (6): exception 'Zend_View_Exception' with message 'script 'index/index/home-user.phtml' not found in path (/home/www/zendphpcertify/application/Front/views/scripts/)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php:988
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('index/index/hom...')
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('index/index/hom...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/index/hom...', NULL)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-10T15:01:38+01:00 INFO (6): exception 'Zend_View_Exception' with message 'script 'index/index/home-user.phtml' not found in path (/home/www/zendphpcertify/application/Front/views/scripts/)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php:988
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('index/index/hom...')
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('index/index/hom...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/index/hom...', NULL)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-10T16:21:08+01:00 INFO (6): exception 'Zend_Controller_Action_Exception' with message 'Action "deconnxion" does not exist and was not trapped in __call()' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php:485
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(518): Zend_Controller_Action->__call('deconnxionActio...', Array)
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('deconnxionActio...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#5 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#6 {main}
2013-01-10T16:21:22+01:00 INFO (6): exception 'Zend_View_Exception' with message 'script 'index/deconnexion.phtml' not found in path (/home/www/zendphpcertify/application/Front/views/scripts/)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php:988
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('index/deconnexi...')
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(900): Zend_View_Abstract->render('index/deconnexi...')
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(921): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/deconnexi...', NULL)
#3 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/Helper/ViewRenderer.php(960): Zend_Controller_Action_Helper_ViewRenderer->render()
#4 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#5 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#6 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('deconnexionActi...')
#7 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#11 {main}
2013-01-11T11:57:24+01:00 INFO (6): exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (css)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#4 {main}
2013-01-11T11:57:26+01:00 INFO (6): exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (css)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#4 {main}
2013-01-11T11:57:26+01:00 INFO (6): exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller specified (css)' in /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Dispatcher/Standard.php:248
Stack trace:
#0 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /usr/local/zend/share/ZendFramework-1.11.12/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /home/www/zendphpcertify/public/index.php(24): Zend_Application->run()
#4 {main}
